# Basic Information 
title: Justus Inhoffen
profession: Financial Economist & Data Scientist
position: Ph.D. Student
affiliation: DIW Berlin; Vrije Universiteit Amsterdam; De Nederlandsche Bank
email: jinhoffen@diw.de
baseurl: ""
url: http://website-justus-inhoffen.web.app

# Plugin settings
plugins:
  - jekyll-minifier
  - jekyll-webp
  - jekyll-last-modified-at
  - jekyll-sitemap

last-modified-at:
    date-format: '%y-%b-%d'

webp:
  enabled: true
  quality: 80
  img_dir: ["/assets/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png"]
  regenerate: false

# Search Engine Optimization (SEO)
seo:
  landing_page_title: Justus Inhoffen
  description: Financial Economist and Data Scientist

# Social Media 
google_scholar: https://scholar.google.com/citations?hl=en&user=oHBuwpsAAAAJ
github_link: https://github.com/jinhoffen
linkedin: https://www.linkedin.com/in/jinhoffen/

social_media:
  - type: google_scholar
    url: https://scholar.google.com/citations?hl=en&user=oHBuwpsAAAAJ
  - type: github
    url: https://github.com/jinhoffen
  - type: linkedin
    url: https://www.linkedin.com/in/jinhoffen/

# Images
avatar: profile.png
favicon: favicon.png
favicon_dark: favicon-dark.png

# Footnote
enable_footnote: false

# The following files will be removed from the generated website.
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor", "README.md", "firebase.json", "package.json", "package-lock.json"]