name: Build Site and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  FIREBASE_PROJECT_ID: website-justus-inhoffen

jobs:
  build_and_deploy:
    name: Build Site and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build Site with Jekyll (production)
        if: github.ref == 'refs/heads/main'
        run: JEKYLL_ENV=production bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
      - name: Build Site with Jekyll (development)
        if: github.event_name == 'pull_request'
        run: bundle exec jekyll build -t
      - name: Run htmlproofer
        run: |
          bundle exec htmlproofer ./_site --allow-missing-href --allow-hash-href --ignore-status-codes 301,302,999
      - name: Deploy to Firebase Hosting
        id: firebase-deploy-prod
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBSITE_JUSTUS_INHOFFEN }}'
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
      - name: Deploy to Firebase Hosting (dev preview channel)
        id: firebase-deploy-preview
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBSITE_JUSTUS_INHOFFEN }}'
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          expires: 7d